title: Yeonsu Sung # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Incident Response Analyst with 3+ years of commercial experience in analytics and bachelor's degree in Convergence Security Engineering from Sungshin Women's University. Previously at Evits Company, a startup. 
  <br><br> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
